#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "mitchellwestQB"
email = "mitchell_west@mckinsey.com"

[ui]
editor = "nvim"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[git]
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
